# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncard.proto\x12\x04\x63\x61rd\" \n\x04\x43\x61rd\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x12\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x32\n\x0b\x43\x61rdService\x12#\n\x07GetCard\x12\n.card.User\x1a\n.card.Card\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CARD']._serialized_start=20
  _globals['_CARD']._serialized_end=52
  _globals['_USER']._serialized_start=54
  _globals['_USER']._serialized_end=72
  _globals['_CARDSERVICE']._serialized_start=74
  _globals['_CARDSERVICE']._serialized_end=124
# @@protoc_insertion_point(module_scope)
