# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import card_pb2 as card__pb2


class CardServiceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCard = channel.unary_unary(
                '/card.CardService/GetCard',
                request_serializer=card__pb2.User.SerializeToString,
                response_deserializer=card__pb2.Card.FromString,
                )


class CardServiceServicer(object):
    """Interface exported by the server.
    """

    def GetCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCard,
                    request_deserializer=card__pb2.User.FromString,
                    response_serializer=card__pb2.Card.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'card.CardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CardService(object):
    """Interface exported by the server.
    """

    @staticmethod
    def GetCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/card.CardService/GetCard',
            card__pb2.User.SerializeToString,
            card__pb2.Card.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
